# http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
# https://github.com/whoshuu/cpr/blob/master/.travis.yml

language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc-debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gdb
      env:
        - COMPILER=g++-5
        - BUILD_TYPE=Debug
    - compiler: gcc-release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gdb
      env:
        - COMPILER=g++-5
        - BUILD_TYPE=Release
    - compiler: clang-debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - gdb
      env:
        - COMPILER=clang++-3.7
        - BUILD_TYPE=Debug
    - compiler: clang-release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - gdb
      env:
        - COMPILER=clang++-3.7
        - BUILD_TYPE=Debug

install:
  - CMAKE_VERSION_MM=3.2
  - CMAKE_VERSION_FULL=$CMAKE_VERSION_MM.2
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget --no-check-certificate http://www.cmake.org/files/v${CMAKE_VERSION_MM}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.sh
      && sudo sh cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update
      && ((brew list -1 | grep -q "^$cmake\$") || brew install cmake)
      && (brew outdated cmake || brew upgrade cmake)
      && cmake --version;
    fi

before_script:
  - export CXX=$COMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

script:
  - make VERBOSE=1 -j
  - bin/bloom-test

notifications:
  email: false
